# Site settings
title:              Yael Ben Shalom - Portfolio
email:              yael.bshalom@gmail.com
description:        "Yael Ben Shalom - Portfolio"
url:                "http://localhost:4000"
baseurl:            /YaelBenShalom.github.io

github_username: YaelBenShalom
LinkedIn_username: Yael Ben Shalom
facebook_username: Yael Ben Shalom

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
